# NOTE: it is UNSAFE to run ANY kind of script when using the pull_request_target trigger!
# DO NOT TOUCH THIS FILE UNLESS THE TRIGGER IS CHANGED.
# See warning in https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.

name: Driver API_VERSION checks
on:
  pull_request_target:
    paths:
      - 'userspace/libscap/engine/bpf/**'
      - 'userspace/libscap/engine/modern_bpf/**'
      - 'userspace/libscap/engine/kmod/**'
      - 'driver/ppm_events_public.h'
      - 'driver/bpf/maps.h'
      - 'driver/modern_bpf/maps/maps.h'

jobs:
  paths-filter:
    runs-on: ubuntu-24.04
    outputs:
      driver_api_changed: ${{ steps.filter.outputs.driver_api }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter
      with:
        filters: |
          driver_api:
            - 'driver/API_VERSION'

  driver-api:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    needs: paths-filter
    if: needs.paths-filter.outputs.driver_api_changed == 'false'
    steps:
      - name: Check driver API_VERSION
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message: |
            Please double check **driver/API_VERSION** file. See [versioning](https://github.com/falcosecurity/libs/blob/master/driver/README.VERSION.md#api-version-number).

            /hold
