name: Deploy Github Pages
on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  kernel-tests-master:
    uses: ./.github/workflows/reusable_kernel_tests.yaml
    secrets: inherit

  perf-libs-master:
    runs-on: [ "self-hosted", "linux", "X64" ]
    steps:
      - name: Checkout Libs ⤵️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run perf
        id: perf
        uses: ./.github/actions/composite-perf

      - name: Archive master perf report
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: perf_report
          retention-days: 30 # 30 days because this is the artifact on master; we need to retain it to be able to properly diff it
          path: |
            ${{ steps.perf.outputs.perf_tests }}
            ${{ steps.perf.outputs.perf_scap }}
            ${{ steps.perf.outputs.heaptrack_tests }}
            ${{ steps.perf.outputs.heaptrack_scap }}
            ${{ steps.perf.outputs.gbench_json }}
          if-no-files-found: error

      - name: Checkout Flamegraph ⤵️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'brendangregg/FlameGraph'
          path: flamegraph
          ref: master

      - name: Generate svg file - perf unit tests
        run: |
          sudo perf script --dsos unit-test-libsinsp -i ${{ steps.perf.outputs.perf_tests }} > perf_tests.perf
          ./flamegraph/stackcollapse-perf.pl perf_tests.perf > perf_tests.folded
          ./flamegraph/flamegraph.pl perf_tests.folded > perf_tests.svg

      - name: Generate svg file - perf scap file
        run: |
          sudo perf script --dsos sinsp-example -i ${{ steps.perf.outputs.perf_scap }} > perf_scap.perf
          ./flamegraph/stackcollapse-perf.pl perf_scap.perf > perf_scap.folded
          ./flamegraph/flamegraph.pl perf_scap.folded > perf_scap.svg

      - name: Generate svg file - heaptrack unit tests
        run: |
          heaptrack_print ${{ steps.perf.outputs.heaptrack_tests }} -F stacks.txt
          ./flamegraph/flamegraph.pl stacks.txt > heaptrack_tests.svg
          rm -rf stacks.txt

      - name: Generate svg file - heaptrack scap file
        run: |
          heaptrack_print ${{ steps.perf.outputs.heaptrack_scap }} -F stacks.txt
          ./flamegraph/flamegraph.pl stacks.txt > heaptrack_scap.svg
          rm -rf stacks.txt

      - name: Upload svg files
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: perf_svg
          path: '*.svg'
          if-no-files-found: error

  deploy-pages:
    needs: [kernel-tests-master,perf-libs-master]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download matrix X64
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: matrix_X64

      - name: Move X64 matrix under docs
        run: mv matrix.md docs/matrix_X64.md

      - name: Download matrix ARM64
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: matrix_ARM64

      - name: Move ARM64 matrix under docs
        run: mv matrix.md docs/matrix_ARM64.md

      - name: Disable Table Of Content for matrixes pages
        run: |
          sed -i '1s/^/---\nhide:\n- toc\n---\n\n/' docs/matrix_X64.md
          sed -i '1s/^/---\nhide:\n- toc\n---\n\n/' docs/matrix_ARM64.md

      - name: Download perf svg files
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: perf_svg

      - name: Generate perf pages
        run: |
          mv perf_tests.svg docs/
          echo '<object data="../perf_tests.svg" type="image/svg+xml" id="perf_unit_tests"></object>' > docs/perf_unit_tests.md
          sed -i '1s/^/---\nhide:\n- toc\n---\n\n/' docs/perf_unit_tests.md
          mv perf_scap.svg docs/
          echo '<object data="../perf_scap.svg" type="image/svg+xml" id="perf_scap_file"></object>' > docs/perf_scap_file.md
          sed -i '1s/^/---\nhide:\n- toc\n---\n\n/' docs/perf_scap_file.md
          mv heaptrack_tests.svg docs/
          echo '<object data="../heaptrack_tests.svg" type="image/svg+xml" id="heaptrack_unit_tests"></object>' > docs/heaptrack_unit_tests.md
          sed -i '1s/^/---\nhide:\n- toc\n---\n\n/' docs/heaptrack_unit_tests.md
          mv heaptrack_scap.svg docs/
          echo '<object data="../heaptrack_scap.svg" type="image/svg+xml" id="heaptrack_scap_file"></object>' > docs/heaptrack_scap_file.md
          sed -i '1s/^/---\nhide:\n- toc\n---\n\n/' docs/heaptrack_scap_file.md

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.x

      - run: pip install mkdocs mkdocs-material

      - run: mkdocs build

      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: 'site'

      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5